server:
  port: 8019
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GantyRex
    username: postgres
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true